export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  date: string;
  image: string;
  content: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'como-mantener-mac-rapido',
    title: 'Cómo mantener tu Mac siempre rápido',
    description: 'Cinco hábitos que marcan la diferencia entre un Mac que dura años y uno que empieza a fallar al tercer año.',
    category: 'Preventivo',
    tags: ['Mac', 'Mantenimiento'],
    date: '2026-05-20',
    image: 'https://images.pexels.com/photos/6930431/pexels-photo-6930431.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      '¿Tu Mac va más lento que el primer día? No es necesariamente cosa de la edad del equipo: en la mayoría de los casos es una combinación de hábitos que se pueden corregir en una tarde.',
      'Las cinco causas más habituales que vemos en Soporte Granada son: el disco casi lleno (macOS necesita espacio libre para gestionar memoria virtual y caché), demasiadas apps abriéndose automáticamente al iniciar sesión, extensiones del Finder o utilidades de terceros corriendo en segundo plano, una versión de macOS desactualizada con parches de rendimiento pendientes, y navegadores con decenas de pestañas y extensiones acumuladas.',
      'Antes de gastar dinero en una ampliación de RAM o un disco nuevo, revisa el Monitor de Actividad (Aplicaciones > Utilidades > Monitor de Actividad): te dice exactamente qué proceso está consumiendo CPU o memoria en este momento, y muchas veces el culpable es una sola app mal cerrada.',
      'Mantener macOS actualizado también importa más de lo que parece: Apple publica mejoras de rendimiento y corrección de fugas de memoria en sus [actualizaciones de software](https://support.apple.com/es-es/HT201541), no solo parches de seguridad. Antes de actualizar, comprueba siempre la compatibilidad de tus apps clave y haz una copia de seguridad completa.',
      'Otro hábito que marca la diferencia: revisa qué apps se abren solas al encender el Mac, en Ajustes del Sistema > General > Elementos de inicio. Es habitual encontrar ahí utilidades que instalaste hace años y ya no recuerdas para qué sirven.',
      'Si después de limpiar espacio, revisar elementos de inicio y actualizar el sistema tu Mac sigue yendo lento, puede ser un problema de hardware (disco mecánico antiguo, batería degradada) o de software más profundo. En ese caso, una sesión de diagnóstico identifica la causa exacta antes de gastar en piezas que no son el problema.',
    ],
  },
  {
    slug: 'backup-icloud-vs-time-machine',
    title: 'iCloud vs Time Machine: ¿cuál necesitas (o los dos)?',
    description: 'Muchos usuarios creen que iCloud es suficiente como copia de seguridad. Aquí te explicamos por qué no lo es.',
    category: 'Consejos',
    tags: ['Mac', 'Backup'],
    date: '2026-05-10',
    image: 'https://images.pexels.com/photos/5951759/pexels-photo-5951759.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'Muchos usuarios creen que tener iCloud activado ya es suficiente copia de seguridad. Es un error que cuesta caro: iCloud y Time Machine cubren necesidades distintas, y la protección real está en combinarlos.',
      '[iCloud](https://www.apple.com/icloud/) sincroniza tus archivos, fotos y datos de apps entre dispositivos Apple. Si borras un archivo por error, ese borrado también se sincroniza: iCloud no es un histórico de versiones completo, es una copia espejo. Tiene una papelera de 30 días, pero pasado ese plazo el archivo desaparece para siempre.',
      'Time Machine, en cambio, es la herramienta de copia de seguridad nativa de macOS y guarda versiones de tus archivos a lo largo del tiempo en un disco externo. Si necesitas recuperar un documento tal y como estaba hace tres semanas, Time Machine puede hacerlo; iCloud no.',
      'La diferencia clave: iCloud te protege si pierdes el dispositivo (tus datos siguen en la nube), Time Machine te protege si algo se corrompe o lo borras sin querer (puedes volver atrás en el tiempo). Son complementarios, no sustitutos.',
      'Nuestra recomendación profesional, la regla 3-2-1: al menos tres copias de tus datos, en dos soportes distintos, con una copia fuera de casa. En la práctica para un usuario doméstico: el propio Mac, un disco externo con Time Machine, y iCloud (u otra nube) como copia remota.',
      'En Soporte Granada configuramos Time Machine correctamente (incluyendo cifrado del disco de respaldo), revisamos que iCloud esté sincronizando lo que de verdad importa, y comprobamos que las copias funcionan haciendo una restauración de prueba — porque una copia que nunca has probado no es una copia.',
    ],
  },
  {
    slug: 'malware-en-mac-senales',
    title: '¿Tiene tu Mac malware? Las señales que no debes ignorar',
    description: 'El malware en Mac existe y es cada vez más sofisticado. Aquí van las señales de alerta más comunes.',
    category: 'Seguridad',
    tags: ['Mac', 'Seguridad'],
    date: '2026-04-28',
    image: 'https://images.pexels.com/photos/177598/pexels-photo-177598.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      '«Los Mac no tienen virus» es uno de los mitos más caros de la informática. macOS es más seguro que otros sistemas por diseño, pero el malware y el adware existen, y cada año son más sofisticados.',
      'Las señales más claras de que algo no va bien: el navegador cambia de página de inicio o buscador sin que lo hayas tocado, aparecen barras de herramientas o extensiones que no instalaste, ves anuncios emergentes incluso fuera del navegador, el Mac va notablemente más lento de golpe, o el ventilador suena a máxima velocidad sin que estés haciendo nada pesado.',
      'La mayoría de las infecciones en Mac no llegan por virus clásicos, sino por adware empaquetado con descargas de fuentes no oficiales (cracks, instaladores de apps gratuitas con «extras» ocultos) o por perfiles de configuración maliciosos que se instalan tras aceptar un permiso sin leerlo.',
      '[Apple recomienda](https://support.apple.com/es-es/guide/security/welcome/web) revisar regularmente las extensiones del navegador, los perfiles de configuración instalados (Ajustes del Sistema > Privacidad y seguridad > Perfiles) y mantener Gatekeeper activado, que es la protección nativa que impide ejecutar apps de fuentes no identificadas sin tu permiso explícito.',
      'Si sospechas que tu Mac está infectado, no instales el primer «limpiador» que encuentres buscando en Google — varios de esos limpiadores son ellos mismos el problema. Lo seguro es revisar manualmente la carpeta de Aplicaciones, los elementos de inicio y los perfiles de configuración, o pedir ayuda a alguien que sepa dónde mirar.',
      'En Soporte Granada limpiamos el equipo a fondo, eliminamos el adware y los perfiles no deseados, y reforzamos la configuración de seguridad para que no vuelva a pasar — sin venderte una suscripción anual a un antivirus que en macOS rara vez hace falta.',
    ],
  },
  {
    slug: 'actualizar-macos-sin-perder-datos',
    title: 'Actualizar macOS sin miedo: guía paso a paso',
    description: 'Actualizar el sistema operativo no tiene que ser una aventura. Así lo hacemos nosotros con cada cliente.',
    category: 'Tutoriales',
    tags: ['Mac', 'Mantenimiento'],
    date: '2026-04-15',
    image: 'https://images.pexels.com/photos/8374287/pexels-photo-8374287.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'Cada otoño Apple lanza una nueva versión de macOS, y cada otoño llega la misma duda: ¿actualizo ya o espero? La respuesta corta: depende de tu equipo y de las apps que uses a diario, pero casi siempre conviene actualizar con un poco de método.',
      'Antes de pulsar «actualizar», haz siempre estos tres pasos: comprueba que tu Mac aparece en la lista de [equipos compatibles](https://support.apple.com/es-es/HT213264) con la nueva versión, revisa que las apps que usas para trabajar (no solo las de ocio) tienen una versión compatible publicada por su desarrollador, y haz una copia de seguridad completa con Time Machine — no una copia parcial, completa.',
      'Las actualizaciones «point» (de 15.1 a 15.2, por ejemplo) suelen ser seguras y conviene instalarlas pronto porque corrigen fallos de seguridad. Las actualizaciones «major» (de 14 a 15) merecen más cautela, sobre todo si dependes de software profesional específico: estos suelen tardar semanas en publicar la versión compatible.',
      'Si la actualización falla a mitad de proceso o el Mac se queda con la barra de progreso parada mucho tiempo, no apagues el equipo a la fuerza salvo que lleve más de una hora sin moverse. El Modo de Recuperación de macOS permite reinstalar el sistema sin perder los datos del usuario en la mayoría de los casos.',
      'Después de actualizar, revisa los permisos de privacidad (Ajustes del Sistema > Privacidad y seguridad): macOS suele resetear algunos permisos de apps tras una actualización mayor, y es habitual que algo deje de funcionar simplemente porque perdió el permiso de acceso a disco o cámara.',
      'Si prefieres no arriesgarte, en Soporte Granada hacemos la actualización por ti: comprobamos compatibilidad, hacemos copia de seguridad previa, actualizamos y verificamos que todo sigue funcionando antes de darte el equipo de vuelta.',
    ],
  },
  {
    slug: 'pc-windows-va-lento',
    title: 'Por qué tu PC con Windows va lento (y cómo solucionarlo)',
    description: 'Tu PC con Windows va lento sin motivo aparente. Te explicamos las causas más comunes y cómo acelerarlo sin perder datos ni gastar en un equipo nuevo.',
    category: 'Preventivo',
    tags: ['Windows', 'Mantenimiento'],
    date: '2026-06-03',
    image: 'https://images.pexels.com/photos/6958503/pexels-photo-6958503.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      '¿Tu PC tarda una eternidad en arrancar, los programas se quedan colgados o todo se ralentiza con el tiempo? Antes de pensar en comprar uno nuevo, casi siempre hay solución a nivel de software.',
      'Las causas más habituales que vemos en Soporte Granada son: disco casi lleno (Windows necesita espacio libre para funcionar), demasiados programas abriéndose al inicio, un disco duro mecánico (HDD) en lugar de SSD, una instalación de Windows con años de archivos temporales y registro saturado, programas pesados en segundo plano, virus o malware que consumen recursos sin que lo notes, y pocos GB de RAM para el uso que le das hoy.',
      'La buena noticia: la mayoría se resuelve en una sesión de mantenimiento. Liberamos espacio de forma segura, revisamos el inicio de Windows, limpiamos temporales, comprobamos el estado del sistema y eliminamos cualquier software no deseado. En muchos casos, un PC de cinco años vuelve a ir como nuevo.',
      'Una herramienta gratuita que ya viene en Windows y mucha gente no usa: el [Administrador de tareas](https://support.microsoft.com/es-es/windows/usar-el-administrador-de-tareas-de-windows-3f08fc83-e1ca-3a2f-8628-7e22a32aab9a) (Ctrl+Shift+Esc). La pestaña «Inicio» te muestra qué programas arrancan solos con Windows y su impacto real en el arranque; desactivar los que no necesitas a diario es la mejora más rápida y gratis que existe.',
      'Otro clásico: el indexado de búsqueda de Windows puede disparar el uso de disco justo después de instalar programas nuevos o copiar muchos archivos. Es normal que tarde unas horas en estabilizarse; si pasados varios días sigue alto, merece la pena revisarlo.',
      'Si tu PC tiene más de 4-5 años y sigue con un disco duro mecánico (HDD) en lugar de SSD, ahí suele estar el verdadero techo de rendimiento: cambiar a un SSD es la mejora de hardware con mayor impacto percibido en cualquier PC, más incluso que añadir RAM en muchos casos.',
      'Si quieres, hacemos una revisión completa y te decimos exactamente qué está frenando tu equipo, sin venderte piezas que no necesitas.',
    ],
  },
  {
    slug: 'backup-windows-onedrive-vs-copia-local',
    title: 'Copias de seguridad en Windows: OneDrive vs copia local',
    description: '¿OneDrive, Historial de archivos o ambos? Te explicamos cómo hacer copias de seguridad de tu PC para no perder nunca tus archivos, fotos ni proyectos.',
    category: 'Consejos',
    tags: ['Windows', 'Backup'],
    date: '2026-06-05',
    image: 'https://images.pexels.com/photos/18734876/pexels-photo-18734876.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'La pregunta no es si tu PC fallará algún día, sino cuándo. Y el día que pase, lo único que importará es si tenías copia de seguridad. Estas son tus opciones y cuándo usar cada una.',
      'OneDrive guarda tus archivos en la nube de Microsoft y los sincroniza entre dispositivos. Perfecto para documentos, escritorio y fotos, con acceso desde cualquier lugar. Su límite: el espacio gratuito es reducido y no es una copia completa del sistema.',
      'La copia local (Historial de archivos o una imagen del sistema en un disco externo) te permite recuperar versiones anteriores e incluso el equipo entero. Su punto débil: si pierdes el disco o hay un robo, pierdes la copia.',
      'Nuestra recomendación profesional: usa las dos. Copia local para una restauración completa y OneDrive (u otra nube) para tener una copia fuera de casa. Es la regla 3-2-1 aplicada a tu vida digital.',
      '[OneDrive](https://www.microsoft.com/microsoft-365/onedrive/online-cloud-storage) incluye una función llamada «Archivos a petición» que merece la pena activar: mantiene tus archivos visibles en el Explorador pero solo los descarga al disco cuando los abres, liberando espacio sin perder acceso a nada.',
      'Si gestionas varios equipos en casa o en una pequeña empresa, ten en cuenta que el plan gratuito de OneDrive da solo 5 GB — para uso real conviene un plan de pago o aprovechar el 1 TB que ya incluyen las licencias de Microsoft 365 Familiar o Empresa.',
      'En Soporte Granada configuramos el sistema de copias completo por ti y verificamos que de verdad funciona, porque una copia que nunca has probado no es una copia.',
    ],
  },
  {
    slug: 'necesito-antivirus-windows-11-defender',
    title: '¿Necesito antivirus en Windows 11? La verdad sobre Microsoft Defender',
    description: '¿Hace falta un antivirus de pago en Windows 11? Te contamos qué protege Microsoft Defender, cuándo basta y cómo evitar virus y estafas sin gastar de más.',
    category: 'Seguridad',
    tags: ['Windows', 'Seguridad'],
    date: '2026-06-08',
    image: 'https://images.pexels.com/photos/7691721/pexels-photo-7691721.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      '«Hay que comprar un antivirus caro o tu PC se infectará seguro.» Es uno de los mitos que más dinero cuesta. La realidad: Windows 11 incluye Microsoft Defender, una protección sólida y gratuita que para la mayoría de usuarios domésticos es suficiente.',
      'Las amenazas más comunes hoy no son virus clásicos, sino: adware que llena el navegador de anuncios; falsos «optimizadores» que en realidad ralentizan el equipo; ventanas que dicen que tu PC está infectado (y te piden pagar o llamar a un número); y phishing por correo o SMS que busca tus contraseñas y datos bancarios.',
      'Señales de alerta: el navegador cambia de buscador solo, aparecen extensiones o programas que no instalaste, ves pop-ups constantes o el PC va más lento sin razón.',
      'La protección no consiste en acumular antivirus (tener dos a la vez es peor que uno), sino en mantener Windows actualizado, dejar activo Microsoft Defender, descargar solo de fuentes fiables y tener sentido común con correos y enlaces.',
      'Microsoft Defender se actualiza automáticamente varias veces al día a través de Windows Update, sin que tengas que hacer nada — algo que muchos antivirus de pago también hacen, pero cobrando una suscripción anual por ello. Puedes comprobar su estado en Ajustes > Privacidad y seguridad > Seguridad de Windows, o consultar la [documentación oficial de Microsoft](https://support.microsoft.com/es-es/windows/ayuda-con-la-seguridad-de-windows-2ae0363d-0ada-c064-8378-8278f5f435b3).',
      'Si tu empresa necesita protección adicional centralizada para varios equipos, ahí sí tiene sentido dar el salto a una solución de gestión de dispositivos en vez de instalar antivirus de consumo en cada PC por separado.',
      'Si crees que tu PC está infectado, en Soporte Granada lo limpiamos a fondo y lo dejamos seguro, sin software innecesario que te cobre cada año.',
    ],
  },
  {
    slug: 'pasar-datos-pc-nuevo-sin-perder-nada',
    title: 'Cómo pasar tus datos a un PC nuevo sin perder nada',
    description: 'Estrenas PC con Windows. Te explicamos cómo migrar tus archivos, fotos, correo, contraseñas y programas sin perder nada, incluso si vienes de un Mac.',
    category: 'Tutoriales',
    tags: ['Windows', 'Migración'],
    date: '2026-06-10',
    image: 'https://images.pexels.com/photos/5882582/pexels-photo-5882582.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'Estrenar PC es genial... hasta que te das cuenta de que todos tus archivos, programas y contraseñas siguen en el equipo viejo. La buena noticia es que migrar bien tus datos hoy es más sencillo que nunca si se hace con método.',
      'Lo que se puede traspasar sin problema: documentos y carpetas, fotos y vídeos, música, contactos y calendarios, marcadores y, con cuidado, tu correo y contraseñas.',
      'Si usas una cuenta Microsoft y OneDrive, gran parte del proceso es casi automático: inicias sesión en el PC nuevo y tus archivos y ajustes te siguen. Para el resto conviene preparar el equipo de origen, ordenar carpetas y decidir qué programas reinstalar.',
      'Los puntos donde la gente suele tropezar: el correo con cuentas tipo IMAP/Exchange, las contraseñas guardadas en el navegador, las licencias de programas de pago, y —si vienes de un Mac— los formatos de archivo y las apps que no existen en Windows.',
      'Para el correo, si usas Outlook con una cuenta Microsoft 365 o Exchange, los mensajes ya viven en el servidor y solo necesitas volver a iniciar sesión en el PC nuevo. Las cuentas POP son las que más dolores de cabeza dan, porque a menudo el correo solo existe en el PC viejo: revisa esto antes de desconectar el equipo antiguo.',
      'Para las contraseñas guardadas en el navegador, tanto [Chrome](https://support.google.com/chrome/answer/95606) como Edge permiten exportar o sincronizar contraseñas a través de tu cuenta de Google o Microsoft, lo que hace la migración casi automática si ya tenías la sincronización activada antes del cambio.',
      'Si quieres hacerlo sin estrés, en Soporte Granada nos encargamos de la migración completa, dejamos tu PC configurado a tu gusto y te enseñamos lo esencial para que te sientas como en casa desde el primer día.',
    ],
  },
  {
    slug: 'liberar-espacio-windows',
    title: 'Libera espacio en Windows sin borrar lo importante',
    description: '«Espacio en disco insuficiente» en tu PC. Te enseñamos a liberar GB de forma segura sin borrar tus archivos, fotos ni programas importantes.',
    category: 'Preventivo',
    tags: ['Windows', 'Mantenimiento'],
    date: '2026-06-11',
    image: 'https://images.pexels.com/photos/196658/pexels-photo-196658.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'El aviso de «Espacio en disco insuficiente» justo cuando vas a guardar un archivo importante es de los más molestos de Windows. La solución no es borrar tus cosas a ciegas: es entender qué ocupa el espacio.',
      'Lo que más ocupa en un PC suele ser: archivos temporales y de actualizaciones de Windows, la papelera, descargas olvidadas, copias antiguas de Windows (Windows.old), la caché de navegadores y vídeos y fotos sin organizar.',
      'Trucos seguros para ganar espacio: usa el Liberador de espacio y el Sensor de almacenamiento de Windows; vacía la papelera y la carpeta de descargas; elimina copias antiguas del sistema; mueve fotos y vídeos a OneDrive o a un disco externo; y desinstala programas que ya no usas.',
      'Si activas OneDrive con «Archivos a petición», tus documentos están en la nube y solo se descargan cuando los abres. Así liberas espacio sin perder acceso a nada.',
      'Otro punto que se nos olvida: las actualizaciones de Windows antiguas pueden quedarse ocupando varios GB en archivos temporales del sistema. La herramienta «Liberador de espacio en disco» (búscalo en el menú de inicio) tiene una opción para «limpiar archivos del sistema» que elimina esto de forma segura.',
      '¿No te aclaras con qué se puede borrar sin riesgo? En Soporte Granada lo dejamos optimizado y te explicamos cómo mantener el disco despejado. Y si después de limpiar sigues al límite, te lo decimos claro: puede que simplemente el disco se haya quedado pequeño para tu uso actual, y ahí ya hablamos de ampliar almacenamiento, no de limpieza.',
    ],
  },
  {
    slug: 'windows-10-sin-soporte-actualizar-windows-11',
    title: 'Windows 10 ya no tiene soporte: ¿debo pasar a Windows 11?',
    description: 'Windows 10 dejó de recibir soporte en octubre de 2025. Te explicamos qué significa, si tu PC admite Windows 11 y cómo actualizar sin perder tus datos.',
    category: 'Seguridad',
    tags: ['Windows', 'Seguridad'],
    date: '2026-06-12',
    image: 'https://images.pexels.com/photos/326513/pexels-photo-326513.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'Si tu PC sigue con Windows 10, esto te interesa: Microsoft dejó de dar soporte de seguridad a Windows 10 en octubre de 2025. Eso no significa que tu equipo se apague, pero sí que deja de recibir parches frente a nuevas amenazas, lo que con el tiempo lo hace más vulnerable.',
      'Tienes básicamente tres caminos: actualizar a Windows 11 si tu equipo cumple los requisitos; valorar opciones de seguridad adicionales mientras planificas el cambio; o, si el equipo es muy antiguo, plantear su renovación.',
      'Windows 11 pide unos requisitos concretos (entre ellos el chip de seguridad TPM 2.0 y procesadores relativamente recientes). Muchos PCs de los últimos años lo cumplen; otros no. Comprobarlo antes evita sorpresas.',
      'Puedes comprobar la compatibilidad de tu equipo en menos de un minuto con la herramienta de comprobación de [requisitos de Windows 11 de Microsoft](https://www.microsoft.com/es-es/windows/windows-11-specifications), que te dice exactamente qué requisito no cumples si tu PC no es compatible.',
      'Antes de actualizar, siempre: haz una copia de seguridad completa, verifica la compatibilidad de tu equipo y de tus programas clave, y asegúrate de tener espacio libre suficiente.',
      'Si tu equipo no es compatible y decides quedarte en Windows 10 por ahora, Microsoft ofrece un programa de actualizaciones de seguridad extendidas (ESU) de pago durante un tiempo limitado — una solución puente, no permanente. Conviene planificar la renovación del equipo con margen, no esperar al último momento.',
      'En Soporte Granada comprobamos si tu PC admite Windows 11, planificamos la actualización segura con copia previa y, si no es compatible, te damos alternativas claras y sin presión comercial.',
    ],
  },
  {
    slug: 'portatil-surface-estudiantes-configuracion',
    title: 'Portátil o Surface para estudiantes: cómo configurarlo para estudiar mejor',
    description: 'Tienes un portátil o Surface para estudiar pero no le sacas partido. Te enseñamos cómo configurarlo para tomar apuntes, organizarte y rendir más.',
    category: 'Consejos',
    tags: ['Windows', 'Estudiantes'],
    date: '2026-06-13',
    image: 'https://images.pexels.com/photos/6348134/pexels-photo-6348134.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'Un buen portátil o Surface puede ser la mejor herramienta de estudio de tu vida o una máquina lenta y desordenada. La diferencia está en cómo lo configuras. Aquí va lo que recomendamos a los estudiantes que pasan por Soporte Granada.',
      'Para tomar apuntes: OneNote es una mina —cuadernos por asignatura, texto, imágenes y, si tienes pantalla táctil o lápiz, escritura a mano—. Y se sincroniza solo en la nube, así que tienes tus apuntes también en el móvil.',
      'Para organizarte: usa el calendario de Outlook y To Do conectados a tu cuenta, y carpetas claras por asignatura en OneDrive. Activa el «Asistente de concentración» para silenciar notificaciones en horas de estudio.',
      'Para rendir más: configura Microsoft 365 y Teams para trabajos en grupo, separa el correo académico del personal, y haz copia de seguridad automática en OneDrive. Nada de perder un proyecto la noche antes de entregarlo.',
      'Si usas [Microsoft Surface](https://www.microsoft.com/es-es/surface), aprovecha el lápiz para anotar directamente sobre PDFs de apuntes o diapositivas del profesor en OneNote, en vez de imprimir y escanear — ahorra tiempo y mantiene todo buscable.',
      'Un truco más: configura una cuenta de [Microsoft 365 Educación](https://www.microsoft.com/es-es/education/products/office) si tu universidad la ofrece (muchas lo hacen gratis con el correo institucional) — incluye Office completo y 1 TB de OneDrive sin coste adicional para estudiantes.',
      'En Soporte Granada dejamos tu equipo listo para estudiar y te enseñamos cuatro trucos que te ahorrarán horas durante todo el curso. Y sí, con tarifa estudiante.',
    ],
  },
  {
    slug: 'ajustes-privacidad-seguridad-windows',
    title: '5 ajustes de privacidad y seguridad en Windows que deberías revisar',
    description: 'Tu privacidad y seguridad en Windows dependen de unos ajustes que casi nadie revisa. Te mostramos 5 cambios rápidos para proteger tu PC y tus datos.',
    category: 'Seguridad',
    tags: ['Windows', 'Seguridad', 'Privacidad'],
    date: '2026-06-14',
    image: 'https://images.pexels.com/photos/277574/pexels-photo-277574.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'Windows 11 es más seguro que nunca, pero la mejor protección no se activa sola: depende de unos ajustes que la mayoría de usuarios nunca abre. Estos son los cinco que revisamos siempre.',
      'Verificación en dos pasos de tu cuenta Microsoft: imprescindible para que nadie entre aunque tenga tu contraseña. Cifrado del disco con BitLocker: si te roban el portátil, tus datos siguen protegidos. Permisos de apps: revisa qué programas acceden a tu ubicación, cámara, micrófono y contactos. Microsoft Defender y firewall activos y al día, sin antivirus duplicados que entren en conflicto. Copia de seguridad activada (OneDrive + copia local): la mejor defensa frente a ransomware y averías.',
      'Ninguno de estos cambios tarda más de unos minutos, pero juntos marcan una diferencia enorme entre estar expuesto y estar protegido.',
      'Para activar el cifrado de disco, ve a Panel de Control > Cifrado de unidad BitLocker — en la edición Home de Windows esta opción puede no estar disponible directamente; en su lugar Windows usa el «Cifrado de dispositivo», que puedes comprobar en Ajustes > Privacidad y seguridad > Cifrado de dispositivo. Más detalle en la [documentación oficial de Microsoft](https://support.microsoft.com/es-es/windows/cifrado-de-dispositivo-en-windows-ad5dcf4b-dbe0-2331-228f-7925c2a3012d).',
      'La verificación en dos pasos de tu cuenta Microsoft se activa en [account.microsoft.com](https://account.microsoft.com/security), en la sección de seguridad avanzada. Tarda dos minutos y es, con diferencia, el cambio individual que más protege tu cuenta.',
      'Si quieres una revisión completa de privacidad y seguridad de tu PC, en Soporte Granada la hacemos contigo y te dejamos todo bien configurado.',
    ],
  },
  {
    slug: 'microsoft-365-vs-google-workspace-vs-gratis',
    title: 'Microsoft 365, Google Workspace o apps gratis: ¿cuál te conviene?',
    description: '¿Microsoft 365, Google Workspace o alternativas gratuitas? Comparamos las opciones de ofimática para que elijas la mejor según cómo trabajas.',
    category: 'Consejos',
    tags: ['Productividad', 'Empresas'],
    date: '2026-06-15',
    image: 'https://images.pexels.com/photos/8353774/pexels-photo-8353774.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'Word o Documentos de Google, Excel o Hojas de cálculo, Outlook o Gmail... tienes varias opciones de ofimática y elegir bien te ahorra dinero y dolores de cabeza. Esta es nuestra comparativa práctica.',
      '[Microsoft 365](https://www.microsoft.com/es-es/microsoft-365) (Office) es el estándar profesional: Word, Excel, PowerPoint, Outlook y Teams, con la mayor compatibilidad y las funciones más avanzadas, especialmente en Excel. Funciona en escritorio, web y móvil, e incluye 1 TB de OneDrive en sus planes.',
      '[Google Workspace](https://workspace.google.com/intl/es/) brilla en la colaboración en tiempo real y el trabajo desde el navegador. Ideal para equipos, estudiantes y quien vive en la nube, con correo profesional en tu dominio.',
      'Las opciones gratuitas (Office en web, LibreOffice, Google personal) pueden bastar para uso ocasional, aunque suelen quedarse cortas en funciones avanzadas, soporte o compatibilidad total con archivos de empresa.',
      'Un matiz importante en precio: Microsoft 365 Personal/Familiar se vende por suscripción anual con un número de usuarios fijo, mientras que Google Workspace se cobra por usuario y mes — la opción más económica depende de cuántas personas y dispositivos necesites cubrir.',
      'Para uso puntual sin instalar nada, no olvides las versiones web gratuitas: Office.com permite usar Word, Excel y PowerPoint online con una cuenta Microsoft gratuita, sin necesidad de licencia de pago, aunque con menos funciones que la versión de escritorio.',
      'Nuestra recomendación: la mayoría de profesionales y empresas que trabajan con documentos exigentes están mejor con Microsoft 365 por compatibilidad y Excel; los equipos muy colaborativos disfrutan Google. En Soporte Granada te ayudamos a elegir, contratar y configurar la opción que de verdad encaja con tu forma de trabajar.',
    ],
  },
  {
    slug: 'ia-generativa-empresa-copilot-chatgpt-gemini',
    title: 'IA generativa en la empresa: Copilot, ChatGPT o Gemini, ¿por dónde empezar?',
    description: '¿Copilot, ChatGPT o Gemini? Te explicamos qué es la IA generativa en plata y cuál te conviene según las herramientas que ya usa tu empresa.',
    category: 'Consejos',
    tags: ['IA', 'Empresas', 'Productividad'],
    date: '2026-06-16',
    image: 'https://images.pexels.com/photos/16094046/pexels-photo-16094046.jpeg?auto=compress&cs=tinysrgb&w=1260',
    content: [
      'La inteligencia artificial generativa ya no es ciencia ficción ni cosa de programadores: si usas Microsoft 365 o Google Workspace, probablemente ya la tienes a un clic de distancia sin haberla activado todavía.',
      '¿Qué es exactamente, en plata? Son programas entrenados con enormes cantidades de texto que, a partir de lo que les pides en lenguaje normal, generan un borrador de correo, un resumen de un documento largo, una fórmula de Excel o incluso código. No son magia ni piensan por ti: son una herramienta que redacta y resume muy rápido, y que hay que revisar siempre antes de usar el resultado.',
      'Las tres opciones que más nos preguntan en Soporte Granada: [Microsoft Copilot](https://www.microsoft.com/es-es/microsoft-copilot), integrado directamente en Word, Excel, Outlook y Teams si tienes Microsoft 365; [Google Gemini](https://workspace.google.com/solutions/ai/) para Workspace, integrado en Gmail, Docs y Sheets; y [ChatGPT](https://openai.com/chatgpt), independiente de cualquier suite, con plan gratuito y de pago.',
      'Casos de uso reales que vemos en pymes de Granada: redactar y pulir correos en segundos, generar un primer borrador de una propuesta o un informe que luego editas, resumir automáticamente una reunión grabada en Teams o Meet, y pedir un análisis de una hoja de cálculo en lenguaje normal en vez de pelearte con fórmulas.',
      'El punto que de verdad importa para una empresa: la privacidad de los datos. Con los planes empresariales (Copilot para Microsoft 365, Gemini para Workspace), tus datos no se usan para entrenar los modelos públicos y se mantienen dentro de los permisos que ya tiene cada empleado. Con cuentas personales o gratuitas de herramientas sueltas conviene tener más cuidado con qué información subes — nunca pegues datos de clientes, contraseñas o documentos confidenciales en una IA de la que no controlas cómo trata esos datos.',
      'Nuestra recomendación práctica: si ya pagas Microsoft 365 o Google Workspace, activar Copilot o Gemini suele ser el camino más sencillo y seguro, porque ya está integrado con tus datos y tus permisos actuales. Si no usas ninguna de las dos suites, ChatGPT Plus o Team es una buena puerta de entrada independiente.',
      'En Soporte Granada te ayudamos a decidir qué herramienta encaja con lo que ya usa tu empresa, la activamos correctamente y formamos a tu equipo en los usos que de verdad ahorran tiempo — sin venderte un curso de IA de moda que luego no vais a usar.',
    ],
  },
];
